apiVersion: v1
kind: Secret
metadata:
  name: auth-gateway-secret
  namespace: bfe
type: Opaque
stringData:
  MONGODB_URI: "CHANGE_ME"
  SMS_ACCESS_KEY_ID: "CHANGE_ME"
  SMS_ACCESS_KEY_SECRET: "CHANGE_ME"
